// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL9-KO9WdK4fjTGEjOMwWBPxIWkjNePIw',
    appId: '1:20955964616:web:54cbb13692945c79f931fd',
    messagingSenderId: '20955964616',
    projectId: 'app-barber-90445',
    authDomain: 'app-barber-90445.firebaseapp.com',
    storageBucket: 'app-barber-90445.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjdKEXnHct4OKPd6gzlz9IcrbzLH21xuM',
    appId: '1:20955964616:android:cbbdcf26a5a5784cf931fd',
    messagingSenderId: '20955964616',
    projectId: 'app-barber-90445',
    storageBucket: 'app-barber-90445.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOS98OHYWBT7Q-ehY-2VGCY2aT9QLUkBY',
    appId: '1:20955964616:ios:d84912fae5f94830f931fd',
    messagingSenderId: '20955964616',
    projectId: 'app-barber-90445',
    storageBucket: 'app-barber-90445.firebasestorage.app',
    iosBundleId: 'br.com.caiodesenvolvedor.appBarber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOS98OHYWBT7Q-ehY-2VGCY2aT9QLUkBY',
    appId: '1:20955964616:ios:d84912fae5f94830f931fd',
    messagingSenderId: '20955964616',
    projectId: 'app-barber-90445',
    storageBucket: 'app-barber-90445.firebasestorage.app',
    iosBundleId: 'br.com.caiodesenvolvedor.appBarber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL9-KO9WdK4fjTGEjOMwWBPxIWkjNePIw',
    appId: '1:20955964616:web:b0ecc9242914d226f931fd',
    messagingSenderId: '20955964616',
    projectId: 'app-barber-90445',
    authDomain: 'app-barber-90445.firebaseapp.com',
    storageBucket: 'app-barber-90445.firebasestorage.app',
  );
}
