name: app_barber
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.10.0
  local_auth: ^3.0.2
  jwt_decoder: ^2.0.1
  brasil_fields: ^1.19.0
  intl: ^0.20.2
  flutter_localization: ^0.4.1
  font_awesome_flutter: ^11.0.0
  moment_dart: ^5.3.4
  image_picker: ^1.2.3
  open_filex: ^4.7.0
  path_provider: ^2.1.4
  dotted_border: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^3.4.2
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0
  flutter_foreground_task: ^10.0.0
  flutter_local_notifications: ^22.3.0
  mobile_scanner: ^6.0.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
